apiVersion: v1
kind: Secret
metadata:
  name: google-oauth
type: Opaque
data:
  CLIENT_ID: ODg1MzY4MjI4NDgyLTJpYzhkZmxqcjk0bHRmamk5NXNpMWl0c2RkdGhvbHFlLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  CLIENT_SECRET: R09DU1BYLVFqeW4xdExka2tHM1VWemlic2lhaTZ0b1JyUUI=
  REDIRECT_URI: aHR0cHM6Ly9kZXZlbG9wZXJzLmdvb2dsZS5jb20vb2F1dGhwbGF5Z3JvdW5k
  REFRESH_TOKEN: MS8vMDRaLU1tM0RmQ3RkLUNnWUlBUkFBR0FRU053Ri1MOUlyVWk1eFlPeTB6SUJqSTNzY3Vnb1R5Zk92QWE2Rjc0dlJtZTdQaVk0Q0ZtZ2c0Q0JHdHN2VkZxdWk4SFNyTXV0M2dFUQ==
