apiVersion: v1
kind: Secret
metadata:
  name: google-oauth
type: Opaque
data:
  CLIENT_ID: MTAwMzAwODIyMjIwMi05Y2pybHNvZW5zOGk5a205M2U4MjQzM3E0c3Q1OGY3di5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
  CLIENT_SECRET: R09DU1BYLWltaDF4eTcwa3gwMVEwbGhyLWwxSlpNallNYmM=
  REDIRECT_URI: aHR0cHM6Ly9kZXZlbG9wZXJzLmdvb2dsZS5jb20vb2F1dGhwbGF5Z3JvdW5k
  REFRESH_TOKEN: MS8vMDRZNkpUQjVucW1TTkNnWUlBUkFBR0FRU053Ri1MOUlyODhLS2FEN3BRWTV0Q0lSRUV6aVBWYWVEcEpURnd3eEVyVmJqN3d0Z3JsNndITnN0RENLc2ozMW9RYlJYaGpvZmZOcw==
