apiVersion: v1
kind: Secret
metadata:
  name: stripe
type: Opaque
data:
  STRIPE_PUBLIC_KEY: cGtfdGVzdF81MVBSTmppQ1dORlpyaDhlSWhnaUNxRWtVejllZlhZNHBwQkN1c3IzZnpvc3lPMTd6bmU3clA2V0gxY3QzOHpSa0h6SzVncTFyYkE5N1ZZT1pINlpUYWhFbTAwbUluMHlaeFE=
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVBSTmppQ1dORlpyaDhlSUxMYTVMTG1iYnBMYXhnWTZPc01Nd1NQcVlrdVp4ZlpJUFIxNVVoRmdaRVhzZTBtbm0wTGZQY0diQ1RxcmxCUWhqY3lmV0NIaTAwZ3loRGRiM3A=
  
