apiVersion: skaffold/v4beta8
kind: Config
build:
  artifacts:
    - image: uniplanet/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: uniplanet/products
      context: products
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: uniplanet/account
      context: account
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: uniplanet/chat
      context: chat
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: uniplanet/message
      context: message
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/minikube/*
    - ./infra/minikube-dev/*
deploy:
  kubectl: {}
 