apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/auth-url: https://auth.com/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://auth.com/oauth2/start?rd=$escaped_request_uri
spec:
  ingressClassName: nginx
  rules:
    - host: auth.com
      http:
        paths:
          - path: /api/auth/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
    - host: mail.com
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: my-oauth2-proxy
                port:
                  number: 80
    - host: products.com
      http:
        paths:
          - path: /api/products/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: products-srv
                port:
                  number: 3001
