apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOREF6TVRFeQpNVFUxTWpWYUZ3MDBOREF6TVRFeU1UVTFNalZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEVzdib0RnT3cwWmFnZTBTNUlwam9idUtmRkdpekc0SUZwdzdUYnlQRkpkeTJKbmpCWQo2SzB1d2ZqYTY3bGJ2c05aejlSYXFzWWpGMXcwOVhlMktObTZaMmJ4Y1JBRE00ZHR0RzJlVTZ3NE41aUxrNVNDCmZPQy9YaU5VOExvQklIMkF5RDBkcWdnU0hYTUtNWFBzcC9OcGYrT20wenF5YU1vSDIxR004Y1JjeFpGRjVhMjkKdnc1RHFMeFBBNTRaOThzNGovd3hkbUI4Z2I5REZRT0xtVFliZm95YWFiN0xXa2JmRzNJRHc4NTlxNDFJLzlTVQpBekl3ZjRaQmg5THJ4N04yTzlRM2QrdC9oa3V2ZWE2NEFFTWVuSEpwK3lmMjkxdURDcjg2Yi93UlU4aUVML2xwCnFCTCs1Sis1OFRGME93eG5zSnFhblN1NUJKYmtKUEtPTUc4bEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFGWi9BU0sxcjJrZ2ZZRVFHZgpJZ3VuUVYwcEpqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEweERUNENnWStIaXBnZlpmQXRTOFBRT1ZVY2xICnZUV05MQzBvVzFCQS9YUGg2OVRud3VWeU1VT0dQSjlPRFducC82N0VpMEorSHB2UjRnL2tXWHFwRWNYMmdueEMKQityV0V5Zms4WFcwN3dPWkZaelNzbzFoeUsybGplQnlLOFRydFdBN2lhV1ZtYVZYM25xb3BVTHVja0pVVzd3Wgp2eGJDYklOWHNtaUZtaHJOanMyTVdHUWR1NjBjRmNqa29YWjE5Vmt6bEUyemtneDIxL3VSQXBHeVhvdjYrWEpBCjRFK0s3Tyt2M0NSaWFiZFQ5aVEzSGNFcHdUYy84RzAxTnVWR0ZScXhQbUJXdkFFd2xRYmN1enh0TnhhUDFYQlYKKy9uU3dISU1DdUVwS0pMWHYvNzhnK0hoanNqSHIxOUZyVHNyNDk3VENKTFZHc0IyV0IzR1lXMjNoQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://62cc314b-eb70-45ca-b97f-4b7e8f514c95.k8s.ondigitalocean.com
  name: do-nyc1-unipalnet
contexts:
- context:
    cluster: do-nyc1-unipalnet
    user: do-nyc1-unipalnet-admin
  name: do-nyc1-unipalnet
current-context: do-nyc1-unipalnet
kind: Config
preferences: {}
users:
- name: do-nyc1-unipalnet-admin
  user:
    token: dop_v1_d12142bf873705f023278bd0625c474585600cc6bbe9cc1862a8cb61e5527569
