apiVersion: v1
kind: Secret
metadata:
  name: cloudinary
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHRnbW1mdjNk
  CLOUDINARY_API_KEY: NTIzNjkyNTgxNzkzNjk1
  CLOUDINARY_API_SECRET: VmxqX1c1bXB3QmhsZWxzNVZDeFJNbWFoVm5R
