apiVersion: v1
kind: Secret
metadata:
  name: stripe
type: Opaque
data:
  STRIPE_PUBLIC_KEY: cGtfbGl2ZV81MVBSTmppQ1dORlpyaDhlSTg4bzNvOXk1YUFXSW5JRnlqRnpWTEJ0djJsTkFXV1A5MUE0ZGpPamRZMTJxdVU0TEVuekZkakx2amJ4SElUeFd5SGFidGpYYzAwWXNYR1hzdm0=
  STRIPE_SECRET_KEY: c2tfbGl2ZV81MVBSTmppQ1dORlpyaDhlSWFINzdtY2tvSXFHTEhwM29heWw3amtXQlJ2cjk2TUZKdVgxQURZVnpvM01ydEV4U2x0SlFaR1NPcndFaDBXTTZKVWhidU15WjAweTZIYkRtYTI=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfald0bFJpQlJqM0NoRmF1Vmo0Z0lZdllYVGtoVGNva1k=
