apiVersion: v1
kind: Secret
metadata:
  name: stripe
type: Opaque
data:
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVBSTmppQ1dORlpyaDhlSUxMYTVMTG1iYnBMYXhnWTZPc01Nd1NQcVlrdVp4ZlpJUFIxNVVoRmdaRVhzZTBtbm0wTGZQY0diQ1RxcmxCUWhqY3lmV0NIaTAwZ3loRGRiM3A=
