apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-depl
spec:
  replicas: 1
  selector: # letting deployment know what app should dealing with
    matchLabels:
      app: chat
  template: # specify exact configuration of the pod we want to deployment to create
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: uniplanet/chat
          resources:
            limits:
              memory: 250Mi
              cpu: "200m"
            requests:
               memory: 200Mi
               cpu: "150m"
          env:
            - name: MONGO_DB_HOST
              value: "mongodb://chat-mongo-srv:27017/chat"
            - name: COOKIE_SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: COOKIE_SESSION_KEY
            - name: KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: KAFKA_BROKER

            - name: JWT_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_TOKEN_SECRET
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_PORT
            - name: DEVELOPMENT_MODE
              valueFrom:
                secretKeyRef:
                  name: development-mode
                  key: DEVELOPMENT_MODE
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: fcm-auth
                  key: FIREBASE_CLIENT_EMAIL
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: fcm-auth
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: fcm-auth
                  key: FIREBASE_PRIVATE_KEY
            - name: FIREBASE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: fcm-auth
                  key: FIREBASE_STORAGE_BUCKET

---
apiVersion: v1
kind: Service
metadata:
  name: chat-srv
spec: 
  selector:
    app: chat
  ports:
    - name: chat
      protocol: TCP
      port: 3003
      targetPort: 3003
