apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector: # letting deployment know what app should dealing with
    matchLabels:
      app: auth
  template: # specify exact configuration of the pod we want to deployment to create
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: uniplanet/auth:latest
          # image: us.gcr.io/sigma-composite-408000/auth:latest
          resources:
            limits:
              memory: 256Mi
              cpu: "0.2"
            requests:
              memory: 256Mi
              cpu: "0.2"
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_TOKEN_SECRET
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: gmail-api
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: gmail-api
                  key: SMTP_PORT
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: gmail-api
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gmail-api
                  key: CLIENT_SECRET
            - name: REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: gmail-api
                  key: REDIRECT_URI
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gmail-api
                  key: REFRESH_TOKEN
            - name: OTP_KEY
              valueFrom:
                secretKeyRef:
                  name: gmail-api
                  key: OTP_KEY
            - name: REDIS_HOST
              value: auth-redis-srv
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
