apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector: # letting deployment know what app should dealing with
    matchLabels:
      app: products
  template: # specify exact configuration of the pod we want to deployment to create
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: uniplanet/products
          resources:
            limits:
              memory: 250Mi
              cpu: "200m"
            requests:
              memory: 200Mi
              cpu: "150m"
          env:
            - name: MONGO_DB_HOST
              value: "mongodb://products-mongo-srv:27017/products"
            - name: KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: KAFKA_BROKER
            - name: JWT_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_TOKEN_SECRET

            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: smtp-config
                  key: SMTP_PORT
            - name: SMTP_MODE
              valueFrom:
                secretKeyRef:
                  name: smtp-config
                  key: SMTP_MODE

            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-oauth
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-oauth
                  key: CLIENT_SECRET
            - name: REDIRECT_URI           
              valueFrom:
                secretKeyRef:
                  name: google-oauth
                  key: REDIRECT_URI
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google-oauth
                  key: REFRESH_TOKEN

            - name: OTP_KEY
              valueFrom:
                secretKeyRef:
                  name: utils
                  key: OTP_KEY
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_PORT
            - name: MONGO_DB
              value: mongodb://products-mongo-srv:27017/products
---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 3001
      targetPort: 3001
