export const GET_PRODUCT_ROUTE = '/api/product/get-product'
export const UPLOAD_PRODUCT_ROUTE = '/api/product/upload-product'
export const DELETE_PRODUCT_ROUTE = '/api/product/delete-product'
export const UPDATE_PRODUCT_ROUTE = '/api/product/update-product'
export const SEARCH_PRODUCT_ROUTE = '/api/product/search-product'
