apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-redis-depl
  namespace: session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-redis
  template:
    metadata:
      labels:
        app: session-redis
    spec:
      containers:
        - name: session-redis
          image: redis
          resources:
            limits:
              memory: 50Mi
              cpu: "100m"
            requests:
              memory: 30Mi
              cpu: "50m"
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: session-redis-srv
  namespace: session
spec:
  selector:
    app: session-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: session
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-storage
  hostPath:
    path: "/mnt/data/redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: session
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: redis-storage