name: deploy-message
on:
  push:
    branches:
      - main
    paths:
      - "message/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd message && docker build -t uniplanet/message .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push uniplanet/message
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save uniplanet
      - run: kubectl rollout restart deployment message-depl
